Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using Project3_Arrick_WebApp.Models;

namespace Project3_Arrick_WebApp.Controllers
{

	public class LoginController : Controller
    {
		public static Customer_info customer
        {
            get;
            set;
        }
        
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
         

        //VERIFIES LOGIN INFORMATION AND POPULATES PROFILES
        public ActionResult LoggedIn(string Login,string Password)
        {

			customer = new Customer_info();

            CustomerLoginQuerys.customerLogin(Login,Password,customer);
            CustomerLoginQuerys.populateRequests(customer);
            CustomerLoginQuerys.populateServices(customer);

            //if login fails
            if (customer.FName == null)
            {
                return RedirectToAction("Index", "Home");
            }

			ViewBag.CustomerID = customer.ID;
			ViewBag.Login = customer.Login;
			ViewBag.Password = customer.Password;
            return View("LoggedIn",customer);
            
        }
        
        public void EmployeeLoggedIn()
        {

            

        }
    }
}

Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Project3_Arrick_WebApp.Models;

//note..
//Controller name must match View folder and action methods must mutch view file name.. haha

namespace Project3_Arrick_WebApp.Controllers
{
    public class RequestController : Controller
    {
		[HttpPost]
        public IActionResult MakeRequest(bool oil, bool brakes,bool tires,bool fluids,bool detail,bool plugs,
                                         bool belts,bool battery,bool bulbs,string vid,string  make, 
		                                 string model, string year,string notes)
        {
			Request request = new Request(LoginController.customer.ID,make,model,year,vid,notes,"",DateTime.Today.ToString("d"));

			//requested services
			string oil1,brakes1,tires1,fluids1,detail1,plugs1,belts1,battery1,bulbs1;
			oil1 = (oil) ? "Oil Change and Filter" : "";
			brakes1 = (brakes) ? "Brake Pads" : "";
			tires1 = (tires) ? "Tire Rotation" : "";
			fluids1 = (fluids) ? "Fluids" : "";
			detail1 = (detail) ? "Detailing" : "";
			plugs1 = (plugs) ? "Spark Plugs" : "";
			belts1 = (belts) ? "Belt Replacement" : "";
			battery1 = (battery) ? "Battery Replacement" : "";
			bulbs1 = (bulbs) ? "Light Bulbs" : "";
			List<string> services = new List<string>
			{
				oil1,
				brakes1, 
				tires1, 
				fluids1, 
				detail1, 
				plugs1,
				belts1,
				battery1, 
				bulbs1 
			};
            //check which services customer selected and add to request
			foreach (string service in services)
			{
				if(service != ""){
					request.ManageServices.Add(new Service(service,vid,"","Jacob Smith",0.00,false)); // some fields to be edited by mechanic
				}
			}
            
			//make request query
			RequestQuerys.addRequest(request);
			RequestQuerys.addServices(request);
			return RedirectToAction("LoggedIn", "Login",new { Login = LoginController.customer.Login, Password = LoginController.customer.Password} );
        } 

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Login/LoggedIn.cshtml

    @model Project3_Arrick_WebApp.Models.Customer_info

    @{
        ViewData["Title"] = "Logged In";
    }

    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href='@Url.Content("./css/login_styles.css")'/>
        <style>

            body {
                font-family: Arial, Helvetica, sans-serif;
            }


            /* The Modal (background) */
            .modal {
                display: none; /* Hidden by default */
                position: fixed; /* Stay in place */
                z-index: 1; /* Sit on top */
                padding-top: 100px; /* Location of the box */
                left: 0;
                top: 0;
                width: 100%; /* Full width */
                height: 100%; /* Full height */
                overflow: auto; /* Enable scroll if needed */
                background-color: rgb(0,0,0); /* Fallback color */
                background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
            }

            /* Modal Content */
            .modal-content {
                background-color: #fefefe;
                margin: auto;
                padding: 20px;
                border: 1px solid #888;
                width: 80%;
            }

            /* The Close Button */
            .close, .close1 {
                color: #aaaaaa;
                float: right;
                font-size: 28px;
                font-weight: bold;
            }

                .close:hover,
                .close:focus {
                    color: #000;
                    text-decoration: none;
                    cursor: pointer;
                }

            td, th {
                border: 2px solid white;
                padding: 3px;
            }

        .button {
            background-color: black;
            color: white;
            border: none;
        }
        .button:hover {
            box-shadow: 0px 0px 10px 5px;
            position: relative;
            top: 1px;
        }

        </style>    

    </head>


    <body>
        


        <div style="background-color:#DFF4F4;">  
            <div style="width: 100%; background-color: lightgray; padding: 2px">
                <h4 style=" text-align:right">logged in.</h4>
            </div> 
                
        <h2>Profile for @Model.FName @Model.LName </h2>
        <h4>Phone: @Model.Number</h4>
        <h4>ID: @Model.ID</h4>
        <h4>User: @Model.Login</h4>
        <h4>Password: @Model.Password</h4>

        <br>
        <br>
        @{  

		int count = 0;
        <div style="background-color:lightgray; padding:10px; width:100%">
           <h4 style="text-align: center; font-style: italic">Make a new service request for a unique vehicle</h4>
           <button style="margin-left: auto; margin-right: auto; display:block" class="button" onclick="openPop(@count)">Make a new Request</button>
        </div>
        <div id="requestModal" class="modal">
            <div class="modal-content" style="background-color:#DFF4F4;">
                
                <button align="right" class="close" onclick="closePop(@count)">X</button>

                <h2>Request Services for a new Vehicle</h2>
                <p> Select all services you would like applied to your vehicle. Please enter all the relevent data including a 
                    valid VID (vehicle identification number) and any pertinent notes for the mechanic. </p>
                @using (Html.BeginForm("MakeRequest", "Request", FormMethod.Post))
                {
                <form>

                    @Html.CheckBox("oil") Oil and Filter Change<br>

                    @Html.CheckBox("brakes") Brake Pads<br>

                    @Html.CheckBox("tires") Tire Rotation<br>

                    @Html.CheckBox("fluids") Fluids<br>

                    @Html.CheckBox("detail") Detailing<br>

                    @Html.CheckBox("plugs") Spark Plugs<br>

                    @Html.CheckBox("belts") Belt Replacement<br>

                    @Html.CheckBox("battery") Battery Replacement<br>

                    @Html.CheckBox("bulbs") Light Bulbs<br>
                    <input type="text" name="vid" placeholder="ENTER VID" required><br>
                    <input type="text" name="make" placeholder="ENTER MAKE"><br>
                    <input type="text" name="model" placeholder="ENTER MODEL"><br>
                    <input type="text" name="year" placeholder="ENTER YEAR"><br>
                    Notes:<br>
                    @Html.TextArea("notes", new { rows = 5, cols = 75 })<br>
                    <input class="button" type="submit" name="submit" value="Submit"><br>
                 </form>
                }
            </div>

        </div>
        }
        <br>
        <br>

        <div style="background-color:lightgray; padding:10px;">
        <h2>Current Requests:</h2>             
        <p style="overflow:auto; font-style: italic">Each request represents services associated with a unique vehicle. 
        When the mechanic has completed all services associated with the particular vehicle, status will change from ACTIVE to COMPLETE.</p>

        @{
            @foreach (var r in @Model.Requests)
            {
                count++;
                <table>
                    <tr>
                        <td>
                            @r.Date
                        </td>
                        <td>
                            <button class=button onclick="openPop(@count)">Request for VID: @r.VID</button>
                        </td>
                        <td style="color:red;">
                            @r.complete()
                        </td>
                    </tr>
                </table>

                <div class="modal" >

                    <div class="modal-content" style="background-color:#DFF4F4;" >
                        <button align="right" class="close" onclick="closePop(@count)">X</button>
                        <h2>Services Requested corresponding to VID: @r.VID </h2>
                        <table style="">
                            <tr> <td>Type</td> <td>Mechanic's Notes</td> <td>Employee Assigned</td> <td>Price for Service</td> </tr>
                            @{
                                foreach (var s in r.ManageServices)
                                {
                                    <tr>
                                        <td>@s.ServiceType</td>
                                        <td>@s.Notes</td>
                                        <td>@s.AssignedEmployeeID</td>
                                        <td>@s.Price</td>
                                    </tr>
                                }
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td>Total:</td>
                                    <td>@r.total()</td>
                                </tr>

                            }
                        </table>
                        <br>
                           <h4> Notes to the Mechanic:</h4>
                           @r.Notes
                           <h4> Notes from the Mechanic:</h4>
                           @r.ServiceNotes
                    </div>
                </div>  
            }
        }
        </div>
        </div>    

        <br>
        <br>

        <script>
            function openPop(count)
            {
                document.getElementsByClassName("modal")[count].style.display = "block";
            }

            function closePop(count)
            {
                document.getElementsByClassName("modal")[count].style.display = "none";
            }     
        </script>


    </body>