Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Project3_Arrick_WebApp.Models;

//note..
//Controller name must match View folder and action methods must mutch view file name.. haha

namespace Project3_Arrick_WebApp.Controllers
{
    public class EmployeeController : Controller
    {
		[HttpPost]
		public IActionResult Submit(IFormCollection collection)
        {
            
			string vid = Request.Form["vid"];
			string notes = Request.Form["ServiceNotes"];
			string[] list = Service.getServiceList();

			foreach (var x in list)
			{
				Debug.WriteLine(notes+" <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<");
				if (collection.ContainsKey(x)&&collection[x]!="false")
				{
					EmployeeQuerys.UpdateServices(vid, x, true);

				}
				else if(collection.ContainsKey(x) && collection[x] == "false")
				{
					EmployeeQuerys.UpdateServices(vid, x, false);
				}
			}

			if (notes != null && notes != "" && notes != " ")
			{
				EmployeeQuerys.UpdateRequestNotes(vid, notes);
			}

			Employee employee = new Employee();
            EmployeeLoginQuery.populateCustomerList(employee);

            foreach (var c in employee.cList)
            {

                CustomerLoginQuerys.populateRequests(c);
                CustomerLoginQuerys.populateServices(c);

            }
			                    
			return View("EmployeeLoggedIn",employee);
        } 
        
		public ActionResult login()
        {

            Employee employee = new Employee();
            EmployeeLoginQuery.populateCustomerList(employee);

            foreach (var c in employee.cList)
            {

                CustomerLoginQuerys.populateRequests(c);
                CustomerLoginQuerys.populateServices(c);

            }

			return View("EmployeeLoggedIn",employee);

        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Project3_Arrick_WebApp.Models;

//note..
//Controller name must match View folder and action methods must mutch view file name.. haha

namespace Project3_Arrick_WebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }


        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }


        public IActionResult Contact()
        {
            ViewData["Message"] = "GAAAAAAAAAAA";

            return View();
        }


        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using Project3_Arrick_WebApp.Models;

namespace Project3_Arrick_WebApp.Controllers
{

	public class LoginController : Controller
    {
		public static Customer_info customer
        {
            get;
            set;
        }
        
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
         

        //VERIFIES LOGIN INFORMATION AND POPULATES PROFILES
        public ActionResult LoggedIn(string Login,string Password)
        {

			customer = new Customer_info();

            CustomerLoginQuerys.customerLogin(Login,Password,customer);
            CustomerLoginQuerys.populateRequests(customer);
            CustomerLoginQuerys.populateServices(customer);

            //if login fails
            if (customer.FName == null)
            {
                return RedirectToAction("Index", "Home");
            }

			ViewBag.CustomerID = customer.ID;
			ViewBag.Login = customer.Login;
			ViewBag.Password = customer.Password;
            return View("LoggedIn",customer);
            
        }
        
        public void EmployeeLoggedIn()
        {

            

        }
    }
}

Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using Project3_Arrick_WebApp.Models;

namespace Project3_Arrick_WebApp.Controllers
{
    public class RegistrationController : Controller
    {

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult RegisterForm()
        {

            ViewData["uesrTaken"] = TempData["message"];
            return View("RegisterForm");
        }

        public IActionResult Redirect()
        {
            return RedirectToAction("Index","Home");
        }


        public ActionResult Register(string FName, string LName, string Address, 
		                             string Number, string Login, string Password )
        {

            Customer_info customer = new Customer_info();
            TempData["message"] = "";

            //CHECK FOR USER TAKEN
            var db = DBConnection.Instance();
            db.DatabaseName = "sql9235287";
            if (db.IsConnect())
            {
                
                string query = string.Format("SELECT * FROM Customer_info WHERE Login='{0}'",Login);
                var cmd = new MySqlCommand(query, db.Connection);
                cmd.CommandType = System.Data.CommandType.Text;
                var reader = cmd.ExecuteReader();

                while (reader.Read())
                {
                    if (reader.GetString(5) == Login)
                    {
                        reader.Close();
                        TempData["message"] = "USERNAME TAKEN";
                        return RedirectToAction("RegisterForm");
                    }
                }

                db.Close();
            }

            //RETURN CURRENT ID COUNT FOR NEW ID ASSIGNMENT
            int ID =1;
            db = DBConnection.Instance();
            db.DatabaseName = "sql9235287";
            if (db.IsConnect())
            {

                string query = "SELECT * FROM ID_Count";
                var cmd = new MySqlCommand(query, db.Connection);
                ID += (int)cmd.ExecuteScalar();

                db.Close();
            }

            //REGISTER NEW USER
            db = DBConnection.Instance();
            db.DatabaseName = "sql9235287";
            if (db.IsConnect())
            {
                string insert = string.Format("INSERT INTO Customer_info(FName, LName, Address, Number, ID, Login, Password) VALUES ('{0}','{1}','{2}','{3}','{4}','{5}','{6}')", FName, LName, Address, Number, ID, Login, Password);

                var cmd = new MySqlCommand(insert, db.Connection);
                cmd.CommandType = System.Data.CommandType.Text;
                cmd.ExecuteNonQuery();

                db.Close();
            }

            //UPDATE CURRENT ID COUNT IN TABLE
            db =DBConnection.Instance();
            db.DatabaseName = "sql9235287";
            if (db.IsConnect())
            {
                string update = string.Format("UPDATE ID_Count SET count='{0}'", ID);

                var cmd = new MySqlCommand(update, db.Connection);
                cmd.CommandType = System.Data.CommandType.Text;
                cmd.ExecuteNonQuery();

                db.Close();
            }


            return RedirectToAction("Redirect");

        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<html>

    <head>
        <style>
            #mainDiv {
                border: solid, white;
                padding: 95px;
                background-image: url("/images/road.png")
               
                /*background-image:url("https://www.planwallpaper.com/static/images/198690-texture.jpg")*/
            }

            .loginButt {
                background-color: black;
                color:white;
                border:none;
            }
            .loginButt:hover {
                box-shadow: 0px 0px 10px 1px;
                position: relative;
                top: 1px;
            }
            .bButt {
                background-color: none;
                padding: 5px;
                border: white solid 1px;
                color: white;

            }
             .bButt:hover{
                    opacity: 0.5;
                    color:white;
                    position: relative;
                    top: 1px;
                }

            h1.a {
                text-shadow: 2px 2px 2px #8C8C8C;
            }
            a,a:hover {
                text-decoration:none;
            }
            .box{
                border:none;
                padding:2px;
            }

        </style>   

        <link href="https://fonts.googleapis.com/css?family=Berkshire+Swash" rel="stylesheet">
    </head>    
    
    <body style="background-color:#000000">
        <br>
        <br>


        <div id ="mainDiv" align="center" >
                <h1 class="a" style="color:white; font-family: 'Berkshire Swash', cursive; ">Login to book your Service Appointment</h1>
                <br>
                        <!--,FormMethod.Post (might need to add as parameter below)-->
                        @using( Html.BeginForm("LoggedIn","Login")) 
                        {
                            
                            <input class="box" name ="Login" type="text" placeholder="username">
                            <input class="box" name ="Password" type="password" placeholder="password">
                            <input class="loginButt" type="submit" value="Login" />

                        }  
            
 
                    <br>
                    <div style=" text-decoration:none; display:inline-block; padding:3px;">
                        @Html.ActionLink("New Customer Registration", "RegisterForm", "Registration", null, new { @class = "bButt" })
                    </div>
                    <br>
                    <br>

                    <div style="text-decoration:none; display:inline-block; padding:3px;">
                        @Html.ActionLink("Employee Login", "login", "Employee", null, new { @class = "bButt" })
                    </div>
                    <br>
                    <br>

                <!--<div style="background-color:white; height:125px; width:245px; padding-top:3px;" >
                    <iframe style="pointer-events: none;" align="center" src="https://giphy.com/embed/l41YsTNcmT2iaGevS" 
                            width="240" height="120" frameBorder="0" class="giphy-embed">
                    
                    </iframe>
                </div>-->
        </div>

    </body>
</html>    